MACHINE ?= "phyboard-hon"
#MACHINE ?= "phyboard-wega-am335x-1"
#MACHINE ?= "phyboard-hon"

PREMIRRORS:prepend = " \
    git://.*/.*    http://yoctocache/downloads/ \n \
    ftp://.*/.*    http://yoctocache/downloads/ \n \
    http://.*/.*   http://yoctocache/downloads/ \n \
    https://.*/.*  http://yoctocache/downloads/ \n \
"

SSTATE_MIRRORS = "file://.* http://yoctocache/sstate-cache/PATH;downloadfilename=PATH"

# Fuer Training robust ohne Hash Equivalence
BB_HASHSERVE = ""
BB_SIGNATURE_HANDLER = "OEBasicHash"

# Optional: Mirror-Tarballs fuer Git/SCM sauber erzeugen
BB_GENERATE_MIRROR_TARBALLS = "1"
